#!/usr/bin/env python3

import opts
import util
import bibtex
import output
from colorama import init, Fore, Style

# Setup colors
init(autoreset=True)

args = opts.getopts()

logger = util.getlogger('doi2bib', root=True, loglevel=args.loglevel)

logger.debug("Debug logging enabled.")

if args.bibtexdb:
    library = bibtex.read(args.bibtexdb)
    logger.debug(f"Parsed {len(library.entries)} from {args.bibtexdb}.")
else:
    library = bibtex.read('')

dois = list(map(str.strip, args.dois.split(','))) + args.more_dois
if args.doifile:
    dois += util.doifinder(args.doifile)
    logger.debug(dois)

if args.cited:
    dois = bibtex.get_cited(dois)
if args.citing:
    dois = bibtex.get_citing(dois)

added = 0
for doi in dois:
    print('.', end='')
    if not doi:
        continue
    result = util.doitobibtex(doi)
    if result:
        library.add(bibtex.read(result).entries)
        logger.debug(f"Added {doi} to library")
        added += 1
print('')
if added:
    print(f"{Fore.YELLOW}Upadted library with {Style.BRIGHT}{added}{Style.NORMAL} DOIs.")

getattr(output, args.outputmode)(library, args)
